version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo123
    volumes: # für persistente Daten, die einen Neustart überstehen müssen
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: